pipeline {
    agent { docker { image 'php' } }
    stages {
        stage('Composer Install') {
            sh 'composer install'
        }

        stage('PHPUnit') {
            steps {
                sh './vendor/bin/phpunit'
            }
        }
    }
}