pipeline {
    agent none

    stages {
        stage('Composer Install') {
            agent { docker { image 'composer' } }
            steps {
                echo 'Installing Vendor'
                sh 'composer install --working-dir ./PHP/project'
            }
        }

        stage('PHPUnit') {
            agent { docker { image 'php' } }
            steps {
                sh 'pwd'
                sh 'cd ./PHP/project'
                sh 'pwd'
                sh './vendor/bin/phpunit tests'
            }
        }
    }
}